export const baseClasses = {
    fighter:{
        name:"fighter",
        weapons:["axe", "greataxe"],
        ability:[],
        evolveTo:["Raider","Warrior","Hero"],
    },
        soldier:{
        name:"soldier",
        weapons:["Spears","Polearms"],
        ability:[],
        evolveTo:["Hero","Lancer","Scout"],
    },
    skirmisher:{
        name:"skirmisher",
        weapons:["Swords","Greatswords"],
        ability:[],
        evolveTo:["Hunter","Blade","Rogue"],
    },
    defender:{
        name:"defender",
        weapons:["Axes","Swords","Spears"],
        ability:[],
        evolveTo:["Crusader","Knight","Sentinel"],
    },
    archer:{
        name:"archer",
        weapons:["Swords","Bows"],
        ability:[],
        evolveTo:["Scout","Longbowman","Hunter"],
    },
    healer:{
        name:"healer",
        weapons:["Axes","Swords","Spears"],
        ability:[],
        evolveTo:["Priest","Acolyte","Crusader"],
    },
}

export const advancedClasses = {
        raider:{
            name:"raider",
            weapons:["Axes","Swords","Spears"],
            ability:[],
            evolveTo:[
                "Berserker",
                "Warlord",
                "Lionheart",
            ],
        },
        warrior:{
            name:"warrior",
            weapons:["Axes","Swords","Spears"],
            ability:[],
            evolveTo:[
                "Berserker",
                "Warlord",
                "Lionheart",
            ],
        },
        hero:{
            name:"hero",
            weapons:["Axes","Swords","Spears"],
            ability:[],
            evolveTo:[
                "Berserker",
                "Warlord",
                "Lionheart",
                "Marshal",
                "Commando",
            ],
        },
        lancer:{
            name:"lancer",
            weapons:["Axes","Swords","Spears"],
            ability:[],
            evolveTo:[
                "Lionheart",
                "Marshal",
                "Commando",
            ],
        },
        scout:{
            name:"scout",
            weapons:["Axes","Swords","Spears"],
            ability:[],

            evolveTo:[
                "Lionheart",
                "Marshal",
                "Commando",
                "Sniper",
                "Ranger",
            ],

        },
        longbowman:{
            name:"longbowman",
            weapons:["Axes","Swords","Spears"],
            ability:[],
            evolveTo:[
                "Commando",
                "Sniper",
                "Ranger",
            ],
        },
        hunter:{
            name:"hunter",
            weapons:["Axes","Swords","Spears"],
            ability:[],
            evolveTo:[
                "Ranger",
                "Blademaster",
                "Assassin",
                "Commando",
                "Sniper",
                "Ranger",
            ],
        },
        blade:{
            name:"blade",
            weapons:["Axes","Swords","Spears"],
            ability:[],
            evolveTo:[
                "Ranger",
                "Blademaster",
                "Assassin",
            ],
        },
        rogue:{
            name:"rogue",
            weapons:["Axes","Swords","Spears"],
            ability:[],
            evolveTo:[
                "Ranger",
                "Blademaster",
                "Assassin",
            ],
        },
        sentinel:{
            name:"sentinel",
            weapons:["Axes","Swords","Spears"],
            ability:[],
            evolveTo:[
                "Paladin",
                "Champion",
                "Centurion",
            ],
        },
        knight:{
            name:"knight",
            weapons:["Axes","Swords","Spears"],
            ability:[],
            evolveTo:[
                "Paladin",
                "Champion",
                "Centurion",
            ],
        },
        crusader:{
            name:"crusader",
            weapons:["Axes","Swords","Spears"],
            ability:[],
            evolveTo:[
                "Paladin",
                "Champion",
                "Centurion",
                "Saint",
                "Enlightened",
            ],
        },
        priest:{
            name:"priest",
            weapons:["Axes","Swords","Spears"],
            ability:[],
            evolveTo:[
                "Saint",
                "Enlightened",
                "Paladin",
            ],
        },
        acolyte:{
            name:"acolyte",
            weapons:["Axes","Swords","Spears"],
            ability:[],
            evolveTo:[
                "Saint",
                "Enlightened",
                "Paladin",
            ],
        },
}

 


export const exaltedClasses = {
    berserker:{
            name:"berserker",
            weapons:["Axes","Greataxes","Swords"],
            ability:[],
            evolveTo:[],
    },
    warlord:{
            name:"warlord",
            weapons:["Axes","Greataxes","Swords","Greatswords","Spears","Polearms"],
            ability:[],
            evolveTo:[],
    },
    lionheart:{
            name:"lionheart",
            weapons:["Axes","Swords","Spears","Greatswords"],
            ability:[],
            evolveTo:[],
    },
    marshal:{
            name:"marshal",
            weapons:["Swords","Spears","Polearms","Greataxes"],
            ability:[],
            evolveTo:[],
    },
    commando:{
            name:"commando",
            weapons:["Spears","Swords","Bows"],
            ability:[],
            evolveTo:[],
    },
    sniper:{
            name:"sniper",
            weapons:["Swords","Bows"],
            ability:[],
            evolveTo:[],
    },
    ranger:{
            name:"ranger",
            weapons:["Axes","Swords","Bows"],
            ability:[],
            evolveTo:[],
    },
    blademaster:{
            name:"blademaster",
            weapons:["Swords","Greatswords","Spears","Polearms"],
            ability:[],
            evolveTo:[],
    },
    assassin:{
            name:"assassin",
            weapons:["Swords","Greatswords","Bows"],
            ability:[],
            evolveTo:[],
    },
    centurion:{
            name:"centurion",
            weapons:["Axes","Swords","Spears","Greataxes"],
            ability:[],
            evolveTo:[],
    },
    champion:{
            name:"champion",
            weapons:["Axes","Swords","Spears","Polearms"],
            ability:[],
            evolveTo:[],
    },
    paladin:{
            name:"paladin",
            weapons:["Axes","Swords","Spears","Greataxes"],
            ability:[],
            evolveTo:[],
    },
    saint:{
            name:"saint",
            weapons:["Axes","Swords","Spears"],
            ability:[],
            evolveTo:[],
    },
    enlightened:{
            name:"enlightened",
            weapons:["Axes","Swords","Spears"],
            ability:[],
            evolveTo:[],
    },
}


export const abilities  = {
"Ambush":	"(Passive) When initiating combat without moving, gain 6 ATK and 30 HIT.",
"Aptitude":	"(Passive) Gain 50% more weapon EXP. Gain 1 DMG and 5 HIT for each weapon type at mastery A or higher.",
"Bardic Inspiration":"(Aura) ALL units within 2 tiles gain 3 ATK.",
"Blade Dancer":	"(Passive) When dodging, gain 1 stack, up to 6 stacks. Each stack grants 5 AVD. At max stacks, gain 3 ATK. Lose all stacks if hit.",
"Blood In The Water":"(Passive) Gain 1 MOVE and SPD for every 2 injured enemies, up to 2.",
"Bodyguard":"(Passive) On being hit by an enemy initiating combat, gain 1 stack, up to 5 stacks. Consume all stacks when initiating combat, gaining 1 ATK and 10 HIT per stack.",
"Chemist":"(Passive) On turn start, apply 10  poison for 2 turns to a random enemy within 2 tiles, and remove poison or burn from a random ally within 2 tiles.",
"Deserter":"(Passive) Killing an enemy grants a random amount of Denari between 50-150.",
"Diplomat":"(Aura) Increase EXP gain of units within 2 tiles by 20%.",
"Drunkard":"(Passive) Status effect duration on this unit is doubled. For each status effect, gain 2 STR and SPD, and 1 DEF.",
"Duelist":"(Passive) Gains 2 ATK, 20 HIT and 2 SPD against isolated enemies (no adjacent allies).",
"Energized":"(Passive) After defeating an enemy, gain 2 MOV and 2 SPD until the end of your next turn.",
"Forager":	"(Passive) On turn start, heal 5 health if on a  brush tile. Gain 15 HIT and 2 DMG when on  brush or  mushroom tiles.",
"Fury":	"(Passive) If this unit is hit, gain 3 ATK, 3 SPD, and 2 MOV until the end of your next turn.",
"Gentle Heart":	"(Passive) When using  Mend on an ally, restore half the health restored to the ally to yourself.",
"Guardian":	"(Aura) Injured allies within 2 tiles gain 2 defense.",
"Honorable":"Unused"	,
"Hot Headed":"(Passive) While injured, gain 3 attack.",
"Iron Maiden":"(Passive) On being hit, gain 1 stack, up to 5 stacks. Each stack grants 1 ATK, SPD, DEF and 4 HIT. Lose a stack on round start.",
"Lone Wolf":"(Passive) Gain 20 HIT and AVD when no allied units are within 2 tiles.",
"Loyal":"(Aura) Allies within 2 tiles gain 15 hit chace.",
"Price Of Defiance":"(Aura) Can no longer equip two handed weapons. Increase EXP gain of allies within 2 tiles by 40%.",
"Quick Learner":"(Passive) Gain 50% extra EXP when fighting enemies of a higher level.",
"Resolute":"(Passive) Cannot double attack, nor be double attacked due to AGL differences.",
"Ruthless":"(Passive) Gain 30 hit against injured or  feared enemies.",
"Salvation":"Persuades enemies under 50% HP to leave the battlefield. Ineffective on elites.",
"Smuggler":	"(Aura) Double the weapon refinement boosts of allies within 2 tiles.",
"Specialist": "(Passive) Status effects this unit applies cannot be blocked.",
"Valkyrie's Blessing":"(Aura) Injured allies within 2 tiles gain 15 AVD.",
"Vengeful":"(Passive) Deal 3 extra damage when counter-attacking",
"Wraith":"(Passive) Gain 3 ATK and 20 AVD when  hidden.	",
"Leaping_Strike":"Raider	Leap up to 3 extra tiles to attack an enemy, taking their place, and knocking them into a random adjacent tile. Enemy must have an empty adjacent tile.",
"Bloodlust":"Raider(Passive) For every kill (5 max), gain 1 ATK. Resets every chapter.",
"Crushing Blow":"Warrior	Perform a massive swing, dealing and taking double damage this round of combat. If the unit is defeated,  fear any enemies within 2 tiles of the unit until the end of their next turn.",
"Weapon Master":"Warrior(Passive) The carry weight of weapons is cut in half (rounded down)",
"Heroic Charge":"Hero	Charge an enemy within 3 tiles, knocking aside any units in the path, and  staggering them if they're enemies. Unit gains  fortify equal to 50% of their def, rounded down. Targeted enemy must have an empty tile behind them.",
"Savior":"Hero (Passive) Gain 1 ATK, 5 HIT, and 1 MOV for each injured ally within 3 tiles, up to a max of 3.",
"Skewer":"Lancer Attack an enemy within 2 tiles. Apply 20%  bleed for 3 turns, but lose 3 ATK and 20 HIT.",
"Spear Wall	Lancer":"(Passive) When equipped with a  spear or  polearm, if an enemy enters your zone of control before attacking you, they lose 2 SPD, 15 HIT, and 15 AVD in combat.",
"Exploitive Strike":"Scout (Passive) Gain 2 ATK, 2 SPD, and 15 HIT against enemies affected by a status effect during combat.",
"Keen Eye":"Scout (Passive) At the start of your turn, apply the  Marked status to the enemy with the least HP within 3 tiles, reducing their AVD and DEF.",
"Arched Shot":"	Longbow	Shoot your  bow up to 5 tiles with -10 HIT for each tile traveled.",
"Marksmanship":"Longbow (Passive) For every kill (5 max), gain 5 HIT and 1 SPD. Resets each chapter.",
"Leg Shot":"Hunter	Aim for an enemy's leg, losing 3 DMG, but  rooting them for 1 turn.",
"Light Footed":"Hunter (Passive) Forest and  brush tiles no longer consume movement points. All other Terrain costs 1.",
"Frontal Assault":"	Blade	Attack an enemy three times, regardless of agility. Can only be used when attacking an enemy from the front.",
"Swift Strikes":"Blade (Passive) If this unit would attack multiple times when initiating combat, execute all attacks before the enemy can counter.",
"Concealed Movement":"Rogue (Passive) If there are no enemies within 1 tile on turn start, gain  Hidden, letting you pass through enemy ZoC.",
"From The Shadows":"Rogue (Passive) Enemies cannot counter your  flank attacks. Gain 2 ATK on  flanks and  backstabs.",
"Safeguard":"Sentinel	Swap tiles with an allied unit  fortifying both of you equal to 20% of your defense, rounded down. Regain a charge on defeating a unit in combat.",
"Rear Guard":"Sentinel	(Aura) Remove enemy hit bonuses from  flanks and  backstabs for allies within 2 tiles (including self, still cannot counter  backstabs).",
"Taunt":"Knight	Taunt an enemy within 2 tiles to attack this unit.",
"Sturdy":"Knight (Passive) At the start of a turn, if you moved 2 or less tiles last turn, gain  fortify equal to 20% of your defense (rounded down).",
"Smite":"Crusader	Attack an enemy and heal self and all adjacent allies for all the damage dealt. This attack cannot miss or be countered.",
"Divine Right":"Crusader (Passive) At the start of the turn, heal adjacent allies by 20% of their max health.",
"Healing Light":"Priest	Fully heal an ally and remove any negative status effects. Regain a charge every time this unit fully heals an ally with the  Mend ability.",
"Aiding Effort":"Priest (Passive) If any ally is below 50% health, gain 2 movement points.",
"Vital Points":"Acolyte	Refresh an ally's turn. Regain a charge every third turn.",
"Shared Knowledge":"Acolyte	(Aura) Adjacent allies gain 10 HIT.",
"Indomitable":"	Berserker (Passive) The first time this unit's vitality would reach 0 from an attack each chapter, end combat and gain 50%  fortify for 1 turn and restore half of your vitality.",
"Berserk":"	Berserker (Passive) Gain 1 ATK and 3 AVD for each 5 points of missing vitality.",
"Triumphant_Surge":"Warlord	Fortify self by 25% of your defense and heal to full.  fear all adjacent enemies. Gain a charge every 4 kills. Start with no charges.",
"Battleborn":"Warlord (Passive) The first time each turn this unit overkills an enemy by 10+ DMG, refresh their turn.",
"Against The Odds":"Lionheart (Passive) Gain 1 DEF and SPD for each adjacent enemy.",
"Bravery":"	Lionheart (Passive) When initiating combat, gain an extra attack if adjacent to 2+ enemies.",
"Concussive Blow":"Marshal	Attack an enemy with hilt of your  spear or  polearm,  stunning them for 1 turn, or  staggering them if they're elite. This ability cannot miss. (Total charges: 3)",
"Off Balance":"Marshal (Passive) When equipped with a  spear or  polearm,  stagger enemies entering your ZoC that initiate combat if you can counter-attack.",
"Echo Of Defeat":"Commando (Passive) When defeating an enemy, transfer their  marked and  feared status effects to all adjacent enemies.",
"Thrill Of The Hunt":"Commando (Passive) The first time each turn this unit defeats an enemy who was  marked,  feared, bleeding, or  rooted, refresh their turn.",
"Headshot":"Sniper	Lose 40 HIT to execute an enemy without block. Does not work on elites.",
"Deadeye":"Sniper (Passive) Gain 1 damage with a  bow for every 10 hit chance over 100 against a target.",
"Negate":"Ranger (Passive) Negate any enemy combat modifiers to ATK, DEF, HIT, and AVD during combat. (Including Terrain).",
"Precise Shot":"Ranger (Passive) Always ignore enemy shields when attacking with a  bow.",
"Blade Surge":"Blademaster	Slice through an enemy into the tile behind them. The first time each turn this ability kills an enemy, refresh [their] turn. (Enemy must have an empty tile behind them).",
"Footwork":"Blademaster (Passive) If the unit's speed is 10 higher than the enemy's, gain a third attack.",
"Fight Unseen":"Assassin (Passive)  flank and  backstab bonuses are doubled.",
"Silent Killer":"Assassin (Passive) The first time each turn this unit kills an enemy with a  backstab, refresh their turn.",
"Rally":"Centurion	Fortify adjacent allies for 4 DEF.",
"Strengthen Resolve":" Centurion (Passive)  Fortified allies within 2 tiles gain 3 ATK and 3 SPD.",
"Battle Cry":"Champion	Taunt all enemies within 2 tiles.",
"Daunting":"Champion (Passive)  Taunted enemies within 2 tiles lose 3 DEF.",
"Holy Path":"Paladin (Passive) Not affected by enemy zone of control.",
"Divine Inspiration":"Paladin (Passive) Killing an enemy heals the lowest health adjacent ally for 50% of their max health.",
"Aegis":"Saint	Fortify a unit by their defense for 1 turn.",
"Group Prayer":"Saint	Heal all adjacent allies by half their HP.",
"Martial Insight":"Enlightened	Restore a unit's block. Heal them for the amount of block recovered.",
"Cartography":"Enlightened (Passive) While this unit can act this turn, allies moving through adjacent tiles do not consume movement points (Still affected by ZoC).",
"Back From The Dead":"(Passive) The first time this unit's vitality would reach 0 from an attack each chapter, end combat and gain 10  Fortify and 5  Frenzy for 2 turns and fully restore your vitality.",
"Drakkar's Blessing":"(Passive) Gain 1 ATK, 1 SPD, 3 HIT and 3 AVD for each 10% missing vitality.",
"expert Duelist":"(Passive) Gains 6 ATK and 40 AVD in combat. Bonuses halve if target enemy has 1 adjacent ally, removed with 2+ allies.",
"Heavy Plate Armor":"(Passive) DEF boosted 50% against frontal attacks.",
"Inspiring":"(Passive) While at full health, give allies within 2 tiles +3 ATK/DEF/SPD.",
"Intimidating":"(Passive) Enemies attacked by this unit are  feared for a turn if they have less STR.",
"Invincible":"(Passive) Take no damage from the first 2 rounds of combat each turn. (Multiple hits count as one round of combat).",
"Iron Marshal":"(Passive) Gives self and allies within 3 tiles 4 DEF.",
"Leader":"(Passive) Cannot be  backstabbed.",
"Manipulator":"(Passive) Takes no damage while there are allies within 2 tiles.",
"Martyr":"(Passive) On death, give allies within 3 tiles 4  Frenzy and  Fortify for 2 turns. Deal 25% VIT damage to enemies within 3 tiles.",
"Patient":"(Passive) Gain 1 STR and 5 HIT for each turn in the chapter.",
"Poisoner":"(Passive) Injuring an enemy inflicts 6  poison for 2 turns.",
"Shadowblade":"(Passive) Gain 50 AVD for the first 3 rounds of combat each turn. (Multiple hits count as one round of combat).",
"Stalwart":"(Passive) Fully refresh your shield at the end of each combat.",
"Strong Arm":"(Passive) Injuring an enemy inflicts  stagger for 2 turns.",
"Sure Strike":"(Passive) Guaranteed to hit.",
"Young Lion":"(Passive) Gain 2 ATK/SPD/DEF, and 10 HIT for every enemy within 3 tiles.",
}

export const characters=[
    "Illyana",
    "Talon",
    "Edward",
    "Douglas",
    "Corvin",
    "Melanie",
    "Wesley",
    "Jack",
    "Cassidy",
    "Salvatore",
    "Abigail",
    "Kaelith",
    "Arland",
    "Marcus",
    "Quincy",
    "Reyson",
    "Slyker",
    "Wesley",
    "Finn",
    "Benjen",
    "Sven",
    "Cedric",
    "Jorah",
    "Elias",
    "Mattheus",
    "Hilda",
    "Rho",
    "Shiva",
    "Ajax",
    "Phoebe",
    "Ophelia",
    "August",
]