export const baseClasses = {
    fighter:{
        name:"fighter",
        weapons:["axe", "greataxe"],
        ability:[],
        evolveTo:["Raider","Warrior","Hero"],
    },
        soldier:{
        name:"soldier",
        weapons:["Spears","Polearms"],
        ability:[],
        evolveTo:["Hero","Lancer","Scout"],
    },
    skirmisher:{
        name:"skirmisher",
        weapons:["Swords","Greatswords"],
        ability:[],
        evolveTo:["Hunter","Blade","Rogue"],
    },
    defender:{
        name:"defender",
        weapons:["Axes","Swords","Spears"],
        ability:[],
        evolveTo:["Crusader","Knight","Sentinel"],
    },
    archer:{
        name:"archer",
        weapons:["Swords","Bows"],
        ability:[],
        evolveTo:["Scout","Longbowman","Hunter"],
    },
    healer:{
        name:"healer",
        weapons:["Axes","Swords","Spears"],
        ability:[],
        evolveTo:["Priest","Acolyte","Crusader"],
    },
}

export const advancedClasses = {
        raider:{
            name:"raider",
            weapons:["Axes","Swords","Spears"],
            ability:[],
            evolveTo:[
                "Berserker",
                "Warlord",
                "Lionheart",
            ],
        },
        warrior:{
            name:"warrior",
            weapons:["Axes","Swords","Spears"],
            ability:[],
            evolveTo:[
                "Berserker",
                "Warlord",
                "Lionheart",
            ],
        },
        hero:{
            name:"hero",
            weapons:["Axes","Swords","Spears"],
            ability:[],
            evolveTo:[
                "Berserker",
                "Warlord",
                "Lionheart",
                "Marshal",
                "Commando",
            ],
        },
        lancer:{
            name:"lancer",
            weapons:["Axes","Swords","Spears"],
            ability:[],
            evolveTo:[
                "Lionheart",
                "Marshal",
                "Commando",
            ],
        },
        scout:{
            name:"scout",
            weapons:["Axes","Swords","Spears"],
            ability:[],

            evolveTo:[
                "Lionheart",
                "Marshal",
                "Commando",
                "Sniper",
                "Ranger",
            ],

        },
        longbowman:{
            name:"longbowman",
            weapons:["Axes","Swords","Spears"],
            ability:[],
            evolveTo:[
                "Commando",
                "Sniper",
                "Ranger",
            ],
        },
        hunter:{
            name:"hunter",
            weapons:["Axes","Swords","Spears"],
            ability:[],
            evolveTo:[
                "Ranger",
                "Blademaster",
                "Assassin",
                "Commando",
                "Sniper",
                "Ranger",
            ],
        },
        blade:{
            name:"blade",
            weapons:["Axes","Swords","Spears"],
            ability:[],
            evolveTo:[
                "Ranger",
                "Blademaster",
                "Assassin",
            ],
        },
        rogue:{
            name:"rogue",
            weapons:["Axes","Swords","Spears"],
            ability:[],
            evolveTo:[
                "Ranger",
                "Blademaster",
                "Assassin",
            ],
        },
        sentinel:{
            name:"sentinel",
            weapons:["Axes","Swords","Spears"],
            ability:[],
            evolveTo:[
                "Paladin",
                "Champion",
                "Centurion",
            ],
        },
        knight:{
            name:"knight",
            weapons:["Axes","Swords","Spears"],
            ability:[],
            evolveTo:[
                "Paladin",
                "Champion",
                "Centurion",
            ],
        },
        crusader:{
            name:"crusader",
            weapons:["Axes","Swords","Spears"],
            ability:[],
            evolveTo:[
                "Paladin",
                "Champion",
                "Centurion",
                "Saint",
                "Enlightened",
            ],
        },
        priest:{
            name:"priest",
            weapons:["Axes","Swords","Spears"],
            ability:[],
            evolveTo:[
                "Saint",
                "Enlightened",
                "Paladin",
            ],
        },
        acolyte:{
            name:"acolyte",
            weapons:["Axes","Swords","Spears"],
            ability:[],
            evolveTo:[
                "Saint",
                "Enlightened",
                "Paladin",
            ],
        },
}

 


export const exaltedClasses = {
    berserker:{
            name:"berserker",
            weapons:["Axes","Greataxes","Swords"],
            ability:[],
            evolveTo:[],
    },
    warlord:{
            name:"warlord",
            weapons:["Axes","Greataxes","Swords","Greatswords","Spears","Polearms"],
            ability:[],
            evolveTo:[],
    },
    lionheart:{
            name:"lionheart",
            weapons:["Axes","Swords","Spears","Greatswords"],
            ability:[],
            evolveTo:[],
    },
    marshal:{
            name:"marshal",
            weapons:["Swords","Spears","Polearms","Greataxes"],
            ability:[],
            evolveTo:[],
    },
    commando:{
            name:"commando",
            weapons:["Spears","Swords","Bows"],
            ability:[],
            evolveTo:[],
    },
    sniper:{
            name:"sniper",
            weapons:["Swords","Bows"],
            ability:[],
            evolveTo:[],
    },
    ranger:{
            name:"ranger",
            weapons:["Axes","Swords","Bows"],
            ability:[],
            evolveTo:[],
    },
    blademaster:{
            name:"blademaster",
            weapons:["Swords","Greatswords","Spears","Polearms"],
            ability:[],
            evolveTo:[],
    },
    assassin:{
            name:"assassin",
            weapons:["Swords","Greatswords","Bows"],
            ability:[],
            evolveTo:[],
    },
    centurion:{
            name:"centurion",
            weapons:["Axes","Swords","Spears","Greataxes"],
            ability:[],
            evolveTo:[],
    },
    champion:{
            name:"champion",
            weapons:["Axes","Swords","Spears","Polearms"],
            ability:[],
            evolveTo:[],
    },
    paladin:{
            name:"paladin",
            weapons:["Axes","Swords","Spears","Greataxes"],
            ability:[],
            evolveTo:[],
    },
    saint:{
            name:"saint",
            weapons:["Axes","Swords","Spears"],
            ability:[],
            evolveTo:[],
    },
    enlightened:{
            name:"enlightened",
            weapons:["Axes","Swords","Spears"],
            ability:[],
            evolveTo:[],
    },
}
